name: CI Pipeline

on:
  push:
    branches:
      "developer"

  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

#  test:
#    runs-on: ubuntu-latest
#    needs: install
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Set up Node.js
#        uses: actions/setup-node@v3
#        with:
#          node-version: '18.x'
#
#      - name: Install dependencies
#        run: npm ci
#
#      - name: Run tests
#        run: npm test

#  lint:
#    runs-on: ubuntu-latest
#    needs: install
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Set up Node.js
#        uses: actions/setup-node@v3
#        with:
#          node-version: '18.x'
#
#      - name: Install dependencies
#        run: npm ci
#
#      - name: Run lint
#        run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

  notify:
    runs-on: ubuntu-latest
    needs: [ build]
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Send email notification
        env:
          MAILJET_API_KEY: ${{ secrets.MAILJET_API_KEY }}
          MAILJET_SECRET_KEY: ${{ secrets.MAILJET_SECRET_KEY }}
          TO_EMAIL: 'jeanheberth@souzavieira.com'
          FROM_EMAIL: 'noreply@souzavieira.com'
          REPO_NAME: ${{ github.repository }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_USER: ${{ github.event.pull_request.user.login }}
        run: |
          echo "Sending email notification..."
          cat <<EOF > send_email.py
          import os
          import sendgrid
          from sendgrid.helpers.mail import Mail, Email, To, Content
