name: Restrict Push and Pull Request

on:
  push:
    branches:
      - 'developer'
  pull_request:
    branches:
      - 'main'

jobs:

  allow-pull-request:
    runs-on: ubuntu-latest
    if: github.base_ref == 'main' && github.event_name == 'pull_request'
    steps:
      - name: Allow Pull Request
        run: echo "Pull request to main is allowed"

  restrict-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify push source branch
        id: check_branch
        run: |
          BASE_BRANCH=$(git for-each-ref --format='%(upstream:short)' $(git symbolic-ref -q HEAD))
          echo "::set-output name=base_branch::${BASE_BRANCH}"

      - name: Restrict push to developer
        if: steps.check_branch.outputs.base_branch != 'origin/main'
        run: exit 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

