name: Node.js CI

on:
  push:
    branches:
      "developer"

  pull_request:
    branches: [ "main" ]

jobs:

  allow-pull-request:
    runs-on: ubuntu-latest
    if: github.base_ref == 'main' && github.event_name == 'pull_request'
    steps:
      - name: Allow Pull Request
        run: echo "Pull request to main is allowed"

  restrict-pull-request:
    runs-on: ubuntu-latest
    if: github.base_ref != 'main' && github.event_name == 'pull_request'
    steps:
      - name: Cancel Pull Request
        run: exit 1

  restrict-branch:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Cancel Pull Request
        run: exit 1


  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
