name: Notify Pull Request

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send notification email
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        run: |
          pr_title=$(jq -r '.pull_request.title' "$GITHUB_EVENT_PATH")
          pr_url=$(jq -r '.pull_request.html_url' "$GITHUB_EVENT_PATH")
          pr_user=$(jq -r '.pull_request.user.login' "$GITHUB_EVENT_PATH")
          curl --request POST \
            --url https://api.sendgrid.com/v3/mail/send \
            --header "Authorization: Bearer $SENDGRID_API_KEY" \
            --header "Content-Type: application/json" \
            --data '{
              "personalizations": [
                {
                  "to": [
                    {
                      "email": "jeanheberth19@gmail.com"
                    }
                  ],
                  "subject": "Novo Pull Request: '"$pr_title"'",
                  "dynamic_template_data": {
                    "pr_user": "'"$pr_user"'",
                    "pr_title": "'"$pr_title"'",
                    "pr_url": "'"$pr_url"'"
                  }
                }
              ],
              "from": {
                "email": "noreply@gmail.com"
              },
              "content": [
                {
                  "type": "text/plain",
                  "value": "Um novo pull request foi criado por '"$pr_user"'.\n\nTítulo: '"$pr_title"'\nURL: '"$pr_url"'\n\nPor favor, revise-o."
                }
              ]
            }'
